#!/bin/bash
set -e

# Install Apache if not installed
if ! rpm -q httpd >/dev/null 2>&1; then
  yum install httpd -y
fi

# Start & enable Apache
systemctl start httpd
systemctl enable httpd

# Deploy custom index.html from GitHub
cp index.html /var/www/html/index.html
chmod 644 /var/www/html/index.html
